---
name: Deploy

'on':
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test stage"
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy placeholder"
