---
name: Lint

'on':
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - run: pip install -r requirements-dev.txt
      - run: ruff check src tests
      - run: black --check src tests
      - run: mypy src
