---
name: Security

'on':
  push:
    paths:
      - '**/requirements*.txt'
      - 'pyproject.toml'
  pull_request:
    paths:
      - '**/requirements*.txt'
      - 'pyproject.toml'
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - run: pip install -r requirements-dev.txt
      - name: Bandit
        run: bandit -r src -q
      - name: Secret scan
        uses: gitleaks/gitleaks-action@v2
      - name: pip-audit
        run: pip-audit
